import streamlit as st
import google.generativeai as genai

class SimpleAIAssistant:
    """Простой AI ассистент для генерации описаний"""
        
            def __init__(self, api_key=None):
                    self.api_key = api_key or st.secrets.get("GEMINI_API_KEY", "")
                            if self.api_key:
                                        genai.configure(api_key=self.api_key)
                                                    self.model = genai.GenerativeModel('gemini-pro')
                                                        
                                                            def generate_description(self, model_type, polygons, marketplace):
                                                                    """Генерация описания для маркетплейса"""
                                                                            if not self.api_key:
                                                                                        return self._default_description(model_type, polygons, marketplace)
                                                                                                
                                                                                                        try:
                                                                                                                    prompt = f"""
                                                                                                                                Create a compelling marketplace description for a 3D model.
                                                                                                                                            
                                                                                                                                                        Model: {model_type}
                                                                                                                                                                    Polygons: {polygons}
                                                                                                                                                                                Marketplace: {marketplace}
                                                                                                                                                                                            Style: Low-poly, game-ready
                                                                                                                                                                                                        
                                                                                                                                                                                                                    Include:
                                                                                                                                                                                                                                1. Catchy title
                                                                                                                                                                                                                                            2. 3-4 benefits
                                                                                                                                                                                                                                                        3. Technical specifications
                                                                                                                                                                                                                                                                    4. Suggested price ($5-20)
                                                                                                                                                                                                                                                                                5. 5 relevant tags
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                        Format as JSON.
                                                                                                                                                                                                                                                                                                                    """
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                            response = self.model.generate_content(prompt)
                                                                                                                                                                                                                                                                                                                                                        return response.text
                                                                                                                                                                                                                                                                                                                                                                except:
                                                                                                                                                                                                                                                                                                                                                                            return self._default_description(model_type, polygons, marketplace)
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                    def _default_description(self, model_type, polygons, marketplace):
                                                                                                                                                                                                                                                                                                                                                                                            """Резервное описание если API не доступен"""
                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                "title": f"Low Poly {model_type}",
                                                                                                                                                                                                                                                                                                                                                                                                                            "description": f"Optimized {model_type} model with {polygons} polygons.",
                                                                                                                                                                                                                                                                                                                                                                                                                                        "tags": ["lowpoly", "3d", "game", "asset", model_type.lower()],
                                                                                                                                                                                                                                                                                                                                                                                                                                                    "price": "$9.99",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "features": [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Real-time optimized",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Clean topology",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "UV unwrapped",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Game ready"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }